config/routes.rb
Rails.application.routes.draw do
  resources :records
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'noutati', to: 'static_pages#noutati'
  get 'about', to: 'static_pages#about'
  get 'ajutor', to: 'static_pages#ajutor'
  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient

  validates :judet_spital, presence: true
  validates :localitate_spital, presence: true
  validates :spital, presence: true
  validates :sectia, presence: true
  validates :internat_urgenta, presence: true
  validates :data_internarii, presence: true
  validates :ora_internarii, presence: true
  validates :data_externarii, presence: true
  validates :ora_externarii, presence: true
  validates :numar_zile_spitalizare, presence: true
  validates :numar_zile_concediu, presence: true
  validates :diagnostic_de_trimitere, presence: true
  validates :diagnostic_la_internare, presence: true
  validates :diagnostic_la_72_ore, presence: true
  validates :diagnostic_externare_principal, presence: true
  validates :diagnostic_externare_boli, presence: true
  validates :interventie_tehnica, presence: true
  validates :interventie_boala, presence: true
  validates :interventie_data, presence: true
  validates :stare_la_externare, presence: true
  validates :diagnostic_anatomo_patologic, presence: true
  validates :observatie_clinica, presence: true
  validates :observatie_data, presence: true
  validates :examinari_de_specialitate, presence: true
  validates :examene_cerute, presence: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]

  # GET /records or /records.json
  def index
    records = Record.all.order(created_at: :desc)
    patients = Patient.all.order(created_at: :desc)
    if params[:search].present?
      search_term = "%#{params[:search].downcase}%"
      patient_ids = patients.where("lower(firstname) LIKE ? OR lower(lastname) LIKE ? OR cnp LIKE ?", search_term, search_term, search_term).pluck(:id)
      record_ids = records.where("lower(localitate_spital) LIKE ? OR lower(spital) LIKE ? OR lower(diagnostic_la_internare) LIKE ?", search_term, search_term, search_term).pluck(:id)
      records = records.where(patient_id: patient_ids).or(Record.where(id: record_ids))
      patients = patients.where(id: patient_ids)
    end
    @pagy_records, @records = pagy(records, page_param: :page_records)
    @pagy_patients, @patients = pagy(patients, page_param: :patients)
    respond_to do |format|
      format.js
      format.html
    end
  end
  
  

  # GET /records/1 or /records/1.json
  def show
  end

  # GET /records/new
  def new
    @patient = Patient.find(params[:patient])
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
    @patient = Patient.find(Record.find(params[:id]).patient.id)
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)
    @patient = Patient.find(@record.patient_id)

    respond_to do |format|
      if @record.save
        format.html { redirect_to record_url(@record), notice: "Fisa de observatie clinica a fost creata cu succes." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    @patient = Patient.find(@record.patient.id)
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: "Fisa de observatie clinica a fost modificata cu succes." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url, notice: "Fisa de observatie clinica a fost stearsa cu succes." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(
        :patient_id, :user_id, :judet_spital, :localitate_spital, :spital,
        :sectia, :internat_urgenta, :data_internarii, :ora_internarii, :data_externarii,
        :ora_externarii, :numar_zile_spitalizare, :numar_zile_concediu, :numar_talon_pensie,
        :diagnostic_de_trimitere, :diagnostic_la_internare, :diagnostic_la_72_ore,
        :diagnostic_externare_principal, :diagnostic_externare_boli,
        :interventie_tehnica, :interventie_boala, :interventie_data,
        :stare_la_externare, :decedat, :diagnostic_anatomo_patologic,
        :observatie_clinica, :observatie_data, :examinari_de_specialitate, :examene_cerute,
        :examen_oncologic_cavitate_bucala, :examen_oncologic_tegumente, :examen_oncologic_ganglionare,
        :examen_oncologic_san, :examen_oncologic_genital_feminin, :examen_oncologic_citologie_secretie,
        :examen_oncologic_prostata_rect, :examen_oncologic_alte
      )
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_patient.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><%= patient.lastname %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= patient.firstname %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= patient.cnp %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= patient.varsta %></td>
    <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500">Dr. <%= patient.user.prenume%> <%= patient.user.nume%></td>
  <td class="flex justify-end whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 md:pr-0">
    <%= link_to 'Vizualizare pacient detaliata', patient, class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= link_to 'Adaugare fisa clinica', new_record_path(patient: patient), class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= button_to "Sterge", patient, method: :delete, class: 'text-red-600 hover:text-red-900 pl-1', form: { data: { turbo_confirm: "Sigur doresti sa stergi pacientul/a #{patient.lastname}?" } } %>
  </td>
</tr>

app/views/records/_record.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><%= record.localitate_spital %></td>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><%= record.spital %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= record.patient.cnp %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= record.diagnostic_la_internare %></td>
  <td class="flex justify-end whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 md:pr-0">
    <%= link_to 'Vizualizare detaliata', record, class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= link_to 'Modifica', edit_record_path(record), class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= button_to "Sterge", record, method: :delete, class: 'text-red-600 hover:text-red-900 pl-1', form: { data: { turbo_confirm: "Sigur doresti sa stergi fisa pacientului/ei #{record.patient.lastname}?" } } %>
  </td>
</tr>

app/views/records/edit.html.erb
<% content_for :form, 'records' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
       <div class="sm:flex sm:items-center mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Modifica fisa de observatie clinica a pacientului: <%= "#{@record.patient.firstname} #{@record.patient.lastname}" %></h1>
        <div class="sm:flex-auto">
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <%= link_to 'Inapoi la fisele de observatie clinica', records_path, class:'inline-flex items-center justify-center text-red-600 rounded-md border border-transparent bg-white px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-white-300 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto' %>
        </div>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <%= render "form", record: @record %>
      </div>
    </div>
  </main>
</div>

app/views/records/index.html.erb
<% content_for :form, 'records' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="sm:flex sm:items-center mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Fisele de observatie clinica a pacientilor</h1>
        <div class="sm:flex-auto">
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-4 sm:flex-none">
          <button class="inline-flex items-center justify-center text-red-600 rounded-md border border-transparent bg-white px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-white-300 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto" onclick="openSlideOver()">Adauga fisa Clinica</button>
          <div class="flex justify-center z-10 inset-0 hidden pt-32 overflow-auto transition-opacity" 
              id="slide-over">
            <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block overflow-auto sm:p-0">
              <div class="bg-white rounded-lg shadow-xl mx-auto max-w-7xl px-4 pb-2 sm:px-6 lg:px-8 overflow-x-auto"id="slide-overr">
                <div class="p-4">
                  <h1 class="text-2xl font-bold mb-4">Adauga fisa Clinica</h1>
                  <form onsubmit="return false;">
                    <div class="center pb-2">
                      <div class="relative rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:border-red-600 focus-within:ring-1 focus-within:ring-red-600">
                        <label for="name" class="absolute -top-2 left-2 -mt-px inline-block text-center bg-white px-1 text-xs font-medium text-gray-900">Cauta</label>
                        <input onkeypress='search(event, this);' type="text" name="name" id="searchh" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="Marian Popescu " autofocus>
                      </div>
                    </div>
                      <table id="patients" class="min-w-full divide-y divide-gray-300 overflow-auto">
                        <thead>
                          <tr>
                            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Nume</th>
                            <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Prenume</th>
                            <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">CNP</th>
                            <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Varsta</th>
                            <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Apartine de</th>
                            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 md:pr-0">
                            </th>
                          </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200">
                          <% @patients.each do |patient| %>
                            <%= render partial: "records/patient", locals: { patient: patient } %>
                          <% end %>
                        </tbody>
                      </table>
                  </form>
                  <div class="flex <% if @pagy_patients.pages > 1 %> justify-between<% else %> justify-end<%end%>">
                    <% if @pagy_patients.pages > 1 %>
                      <div class="pt-4 pb-4">
                        <%== pagy_nav(@pagy_patients) %>
                      </div>
                      <%end%>
                    <div class="mt-4">
                      <button class="px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600" onclick="closeSlideOver()">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
  </div>
  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <div class="px-4 sm:px-6 lg:px-8">
          <div class="mt-4 flex flex-col">
            <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                <div class="pb-4">
                  <%= render 'shared/notice_messages' %>
                </div>
                <div class="center pb-2">
                  <div class="relative rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:border-red-600 focus-within:ring-1 focus-within:ring-red-600">
                    <label for="name" class="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900">Cauta</label>
                    <input onkeypress='search(event, this);' type="text" name="name" id="search" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="Marian Popescu">
                  </div>
                </div>
                <table id="records" class="min-w-full divide-y divide-gray-300">
                  <thead>
                    <tr>
                      <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Localitate spital</th>
                      <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Denumire spital</th>
                      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">CNP Pacient</th>
                      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Diagnostic internare</th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 md:pr-0">
                        <span class="sr-only">Modifica</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200">
                    <%= render @records %>
                  </tbody>
                </table>
                  <% if @pagy_records.pages > 1 %>
                    <div class="flex justify-center pt-8">
                      <%== pagy_nav(@pagy_records) %>
                    </div>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
<script>
let isSlideOverOpen = false;
  let timeoutIdSearch;
  function search(event, e){
    clearTimeout(timeoutIdSearch);
    timeoutIdSearch = setTimeout(() => {
      $.ajax({
        url: "/records",
        type: "GET",
        data: {
          search: e.value
        },
        success: function(data) {}
      });
    }, 250);
  }
  function searchh(event, e){
    clearTimeout(timeoutIdSearch);
    timeoutIdSearch = setTimeout(() => {
      $.ajax({
        url: "/patients",
        type: "GET",
        data: {
          search: e.value
        },
        success: function(data) {}
      });
    }, 250);
  }
window.addEventListener('load', function() {
  if (localStorage.getItem('slide-over-active') === 'true' && !slideOverOpened) {
    openSlideOverr();
  }

  const urlParams = new URLSearchParams(window.location.search);
  if (urlParams.has('patients')) {
    openSlideOverr();
  }
});

function openSlideOver() {
  document.getElementById('slide-over').classList.remove('hidden');
  setTimeout(function() {
  document.getElementById('slide-over').classList.add('slide-over-active');
  }, 300);
  document.getElementsByTagName('body')[0].classList.add('slide-over-active');
  setTimeout(function() {
    isSlideOverOpen = true
  }, 1000);
}

function openSlideOverr() {
  document.getElementById('slide-over').classList.remove('hidden');
  document.getElementById('slide-over').classList.add('slide-over-active');
  document.getElementsByTagName('body')[0].classList.add('slide-over-active');  
  setTimeout(function() {
    isSlideOverOpen = true
  }, 1000);
}

function closeSlideOver() {
  document.getElementById('slide-over').classList.remove('slide-over-active');
  setTimeout(function() {
    document.getElementById('slide-over').classList.add('hidden');
  }, 300);
  document.getElementsByTagName('body')[0].classList.remove('slide-over-active');
  isSlideOverOpen = false;
}
const box = document.querySelector("#slide-overr");

document.addEventListener("click", function(event) {
  if (isSlideOverOpen && !box.contains(event.target)) {
    closeSlideOver();
  }
});
  if (window.performance && window.performance.navigation.type === window.performance.navigation.TYPE_RELOAD) {
    window.location.href = '/records';
  }
</script>

app/views/records/index.js.erb
document.getElementById("records").innerHTML = `
<table class="min-w-full divide-y divide-gray-300">
    <thead>
    <tr>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Localitate spital</th>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Denumire spital</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">CNP Pacient</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Diagnostic internare</th>
        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 md:pr-0">
        <span class="sr-only">Modifica</span>
        </th>
    </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
    <%= render @records %>
    </tbody>
</table>
`
document.getElementById("patients").innerHTML = `
<table id="patients" class="min-w-full divide-y divide-gray-300">
    <thead>
        <tr>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Nume</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Prenume</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">CNP</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Varsta</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Apartine de</th>
        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 md:pr-0">
            <span class="sr-only">Modifica</span>
        </th>
        </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
        <%= j render @patients %>
    </tbody>
</table>
`;

app/views/records/new.html.erb
<% content_for :form, 'records' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Creare fisa clinica a <%= "#{@patient.sex == "M" ? "pacientului" : "pacientei"}: #{@patient.firstname} #{@patient.lastname}" %></h1>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <%= render "form", record: @record, patient: @patient %>
      </div>
    </div>
  </main>
</div>

app/views/records/show.html.erb
<% content_for :form, 'records' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="sm:flex sm:items-center mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Fisa de observatie clinica a pacientului: <%= "#{@record.patient.firstname} #{@record.patient.lastname}" %></h1>
        <div class="sm:flex-auto">
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <%= link_to 'Inapoi la fisele de observatie clinica', records_path, class:'inline-flex items-center justify-center text-red-600 rounded-md border border-transparent bg-white px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-white-300 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto' %>
      </div>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <%= render 'shared/notice_messages' %>
        <%= render "show_form", record: @record %>
      </div>
    </div>
  </main>
</div>