config/routes.rb
Rails.application.routes.draw do
  resources :records
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'noutati', to: 'static_pages#noutati'
  get 'about', to: 'static_pages#about'
  get 'ajutor', to: 'static_pages#ajutor'
  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :records, dependent: :destroy

  validates :lastname, presence: true
  validates :firstname, presence: true
  validates :data_nasterii, presence: true
  validates :varsta, numericality: true
  validates :sex, presence: true
  validates :cnp, length: {is: 13}, uniqueness: true
  validates :serie_nr_buletin, length: {is: 8}
  validates :localitate, presence: true
  validates :judet, presence: true
  validates :adresa, presence: true, length: {maximum: 100}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :greutate, numericality: true
  validates :inaltime, numericality: true
  validates :ocupatie, presence: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  def index
    patients = Patient.all.order(created_at: :desc)
    if params[:search].present?
      patients = patients.where("lower(firstname) LIKE ? OR lower(lastname) LIKE ? OR cnp LIKE ?", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")
    end
    @pagy, @patients = pagy(patients)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Pacientul a fost introdus cu succes." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Pacientul a fost modificat cu succes." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Pacientul a fost sters cu succes." }
    end
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(
        :lastname, :firstname, :data_nasterii, :varsta,
        :sex, :cnp, :serie_nr_buletin, :greutate,
        :inaltime, :ocupatie, :localitate, :judet,
        :adresa, :email, :grup_sangvin, :rh, :alergii, :user_id
      )
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_patient.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><%= patient.lastname %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= patient.firstname %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= patient.cnp %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= patient.varsta %></td>
    <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500">Dr. <%= patient.user.prenume%> <%= patient.user.nume%></td>
  <td class="flex justify-end whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 md:pr-0">
    <%= link_to 'Vizualizare detaliata', patient, class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= link_to 'Adaugare fisa clinica', new_record_path(patient: patient), class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= link_to 'Modifica', edit_patient_path(patient), class:'text-red-600 hover:text-red-900 pr-1 pl-1' %> |
    <%= button_to "Sterge", patient, method: :delete, class: 'text-red-600 hover:text-red-900 pl-1', form: { data: { turbo_confirm: "Sigur doresti sa stergi pacientul/a #{patient.lastname}?" } } %>
  </td>
</tr>

app/views/patients/_show_form.html.erb
<%= form_with(model: patient, class: "space-y-6") do |form| %>
  <fieldset disabled>
    <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:p-6">
      <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Date personale</h3>
        </div>
        <div class="mt-5 space-y-6 md:col-span-2 md:mt-0">
          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <label for="company-website" class="block text-sm font-medium text-gray-700">Nume*</label>
              <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.text_field :lastname, placeholder: 'Popescu..', class:'block w-full flex-1 rounded-none rounded-l-md rounded-r-md border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm'%>
              </div>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <label for="company-website" class="block text-sm font-medium text-gray-700">Prenume*</label>
              <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.text_field :firstname, placeholder: 'Marian..', class:'block w-full flex-1 rounded-none rounded-l-md rounded-r-md border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm'%>
              </div>
            </div>
          </div>

          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <label for="cnp" class="block text-sm font-medium text-gray-700">Cod numeric personal*</label>
              <%= form.text_field :cnp, class:'block w-full rounded-none rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
            <div class="col-span-6 sm:col-span-3">
              <label for="serie_buletin" class="block text-sm font-medium text-gray-700">Serie si numar card identitate*</label>
              <%= form.text_field :serie_nr_buletin, class:'rounded-none rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
          </div>

          <div class="inline-flex">
            <div class="mr-5">
              <label for="data_nasterii" class="block text-sm font-medium text-gray-700">Data nasterii*</label>
              <%= form.date_field :data_nasterii, max: Date.today, class:'rounded-none rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
            <div>
              <label for="varsta" class="block text-sm font-medium text-gray-700">Varsta*</label>
              <%= form.number_field :varsta, in: 0..130, step: 1, class:'rounded-none rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
          </div>

          <div>
            <label for="sex" class="block text-sm font-medium text-gray-700">Sex*</label>
            <%= form.radio_button :sex, "M", class:'rounded-none rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            <%= form.label :masculin, "Masculin", class:'text-sm font-medium text-gray-700 mr-2' %>
            <%= form.radio_button :sex, "F", class:'rounded-none rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            <%= form.label :feminin, "Feminin", class:'text-sm font-medium text-gray-700' %>
          </div>

          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <label for="ocupatie" class="block text-sm font-medium text-gray-700">Ocupatie*</label>
              <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.text_field :ocupatie, placeholder: 'Salariat..', class:'block w-full flex-1 rounded-none rounded-l-md rounded-r-md border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm'%>
              </div>
            </div>
          </div>

          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
              <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.text_field :email, placeholder: 'popescu.marian@email.com', class:'block w-full flex-1 rounded-none rounded-l-md rounded-r-md border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm'%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:p-6">
      <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Date medicale</h3>
        </div>
        <div class="mt-5 md:col-span-2 md:mt-0">
          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <label for="greutate" class="block text-sm font-medium text-gray-700">Greutate*</label>
              <%= form.number_field :greutate, in: 1.0..200.0, step: 0.1, class:'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <label for="inaltime" class="block text-sm font-medium text-gray-700">Inaltime (m)*</label>
              <%= form.number_field :inaltime, in: 0.4..3.0, step: 0.01, class:'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <label for="grup_sangvin" class="block text-sm font-medium text-gray-700">Grupa sangvina</label>
              <%= form.radio_button :grup_sangvin, "0", class:'rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
              <%= form.label :grupa_0, "0", class:'text-sm font-medium text-gray-700 mr-2' %>
              <%= form.radio_button :grup_sangvin, "A", class:'rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
              <%= form.label :grupa_a, "A", class:'text-sm font-medium text-gray-700' %>
              <%= form.radio_button :grup_sangvin, "B", class:'rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
              <%= form.label :grupa_b, "B", class:'text-sm font-medium text-gray-700 mr-2' %>
              <%= form.radio_button :grup_sangvin, "AB", class:'rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
              <%= form.label :grupa_a, "AB", class:'text-sm font-medium text-gray-700' %>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <label for="rh" class="block text-sm font-medium text-gray-700">RH</label>
              <%= form.radio_button :rh, true, class:'rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
              <%= form.label :pozitiv, "Pozitiv", class:'text-sm font-medium text-gray-700 mr-2' %>
              <%= form.radio_button :rh, false, class:'rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
              <%= form.label :negativ, "Negativ", class:'text-sm font-medium text-gray-700' %>
            </div>

            <div class="col-span-6 sm:col-span-6">
              <label for="alergii" class="block text-sm font-medium text-gray-700">Alergii</label>
              <%= form.text_area :alergii, class:'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:p-6">
      <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Domiciliu</h3>
        </div>
        <div class="mt-5 md:col-span-2 md:mt-0">
          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
                <label for="localitate" class="block text-sm font-medium text-gray-700">Localitate*</label>
                <%= form.text_field :localitate, class:'rounded-none w-full rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
            <div class="col-span-6 sm:col-span-3">
                <label for="judet" class="block text-sm font-medium text-gray-700">Judet*</label>
                <%= form.text_field :judet, class:'rounded-none w-full rounded border-gray-300 focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>

            <div class="col-span-6 sm:col-span-6">
              <label for="adresa" class="block text-sm font-medium text-gray-700">Adresa*</label>
              <%= form.text_area :adresa, class:'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="flex justify-end">
  </div>
<% end %>

app/views/patients/edit.html.erb
<% content_for :form, 'patients' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Fisa pacientului: <%= "#{@patient.firstname} #{@patient.lastname}" %></h1>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <%= render "form", patient: @patient %>
      </div>
    </div>
  </main>
</div>

app/views/patients/index.html.erb
<% content_for :form, 'patients' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="sm:flex sm:items-center mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Pacienti</h1>
        <div class="sm:flex-auto">
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <%= link_to 'Adauga pacient', new_patient_path, class:'inline-flex items-center justify-center text-red-600 rounded-md border border-transparent bg-white px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-white-300 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto' %>
        </div>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <div class="px-4 sm:px-6 lg:px-8">
          <div class="mt-4 flex flex-col">
            <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                <div class="pb-4">
                  <%= render 'shared/notice_messages' %>
                </div>
                <div class="center pb-2">
                  <div class="relative rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:border-red-600 focus-within:ring-1 focus-within:ring-red-600">
                    <label for="name" class="absolute -top-2 left-2 -mt-px inline-block text-center bg-white px-1 text-xs font-medium text-gray-900">Cauta</label>
                    <input onkeypress='search(event, this);' type="text" name="name" id="search" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="Marian Popescu " autofocus>
                  </div>
                </div>
                <table id="patients" class="min-w-full divide-y divide-gray-300">
                  <thead>
                    <tr>
                      <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Nume</th>
                      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Prenume</th>
                      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">CNP</th>
                      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Varsta</th>
                      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Apartine de</th>
                      <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 md:pr-0">
                        <span class="sr-only">Modifica</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-200">
                    <%= render @patients %>
                  </tbody>
                </table>
                  <% if @pagy.pages > 1 %>
                    <div class="flex justify-center pt-8">
                      <%== pagy_nav(@pagy) %>
                    </div>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
<script>
  let timeoutIdSearch;
  function search(event, e){
    clearTimeout(timeoutIdSearch);
    timeoutIdSearch = setTimeout(() => {
      $.ajax({
        url: "/patients",
        type: "GET",
        data: {
          search: e.value
        },
        success: function(data) {}
      });
    }, 250);
  }
</script>

app/views/patients/index.js.erb
document.getElementById("patients").innerHTML = `
<table id="patients" class="min-w-full divide-y divide-gray-300">
    <thead>
        <tr>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Nume</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Prenume</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">CNP</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Varsta</th>
        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Apartine de</th>
        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 md:pr-0">
            <span class="sr-only">Modifica</span>
        </th>
        </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
        <%= j render @patients %>
    </tbody>
</table>
`;

app/views/patients/new.html.erb
<% content_for :form, 'patients' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Fisa pacientului</h1>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <%= render "form", patient: @patient %>
      </div>
    </div>
  </main>
</div>

app/views/patients/show.html.erb
<% content_for :form, 'patients' %>
<div class="min-h-full">
  <div class="bg-red-700 pb-32">
    <header class="py-10">
      <div class="sm:flex sm:items-center mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-white">Fisa pacientului: <%= "#{@patient.firstname} #{@patient.lastname}" %></h1>
        <div class="sm:flex-auto">
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <%= link_to 'Inapoi la lista pacientilor', patients_path, class:'inline-flex items-center justify-center text-red-600 rounded-md border border-transparent bg-white px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-white-300 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto' %>
        </div>
      </div>
    </header>
  </div>

  <main class="-mt-32">
    <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
        <%= render 'shared/notice_messages' %>
        <%= render "show_form", patient: @patient %>
      </div>
    </div>
  </main>
</div>